#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 24:00:00
#SBATCH -J canu_genomeassembly
#SBATCH --mail-type=ALL
#SBATCH --mail-user chiara.dallasanta@gmail.com
#SBATCH --reservation=uppmax2022-2-5_2

# Load modules
module load bioinfo-tools
module load canu

# Commands

canu -p genome_assembly -d canu_genomeassembly genomeSize=2.57m -num_threads 2 -pacbio-raw /home/chiar/genome_analysis/data/DNA_raw_data/*
