#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:30:00
#SBATCH -J EggNOG_genome_annotation
#SBATCH --mail-type=ALL
#SBATCH --mail-user chiara.dalla-santa.8949@student.uu.se

module load bioinfo-tools
module load eggnog-mapper/2.1.5

INPUT="/home/chiar/genome_analysis/03_genome_annotation/prokka/annotated_DNA.ffn"
OUT="/home/chiar/genome_analysis/03_genome_annotation/EggNOG"

emapper.py -i $INPUT -o $OUT/EggNOG
